;*******************************************************************
;* Cloth types - Tops
;*******************************************************************
[clothtype-Dress Shirt]
	Check=DressShirt
	attr=Color
		Value=Black
		Value=Blue
		Value=Brown
		Value=Green
		Value=Grey
		Value=Orange
		Value=Pink
		Value=Purple
		Value=Red
		Value=Tan
		Value=White
		Value=Yellow
		Value=?
	attr=Length
		Value=Short Sleeve
		Value=Long Sleeve
	attr=Material
		value=Cloth
		value=Latex
		value=Leather
		value=PVC
	attr=Style
		Value=Tight
		Value=Loose
		Value=Baggy
	attr=Description

[clothtype-Light Shirt]
	Check=LightShirt
	attr=Color
		Value=Black
		Value=Blue
		Value=Brown
		Value=Green
		Value=Grey
		Value=Orange
		Value=Pink
		Value=Purple
		Value=Red
		Value=Tan
		Value=White
		Value=Yellow
		Value=?
	attr=Length
		Value=Sleeveless
		Value=Short Sleeve
		Value=Long Sleeve
	attr=Material
		value=Cloth
		value=Latex
		value=Leather
		value=PVC
	attr=Style
		Value=Tight
		Value=Loose
		Value=Baggy
	attr=Description

[clothtype-Sweater]
	Check=Sweater
	attr=Color
		Value=Black
		Value=Blue
		Value=Brown
		Value=Green
		Value=Grey
		Value=Orange
		Value=Pink
		Value=Purple
		Value=Red
		Value=Tan
		Value=White
		Value=Yellow
		Value=?
	attr=Length
		Value=Sleeveless
		Value=Short Sleeve
		Value=Long Sleeve
	attr=Material
		value=Cloth
		value=Latex
		value=Leather
		value=PVC
	attr=Style
		Value=Tight
		Value=Loose
		Value=Baggy
	attr=Description

[clothtype-T-Shirt]
	Check=T-Shirt
	attr=Color
		Value=Black
		Value=Blue
		Value=Brown
		Value=Green
		Value=Grey
		Value=Orange
		Value=Pink
		Value=Purple
		Value=Red
		Value=Tan
		Value=White
		Value=Yellow
		Value=?
	attr=Length
		Value=Sleeveless
		Value=Short Sleeve
		Value=Long Sleeve
	attr=Material
		value=Cloth
		value=Latex
		value=Leather
		value=PVC
	attr=Style
		Value=Tight
		Value=Loose
		Value=Baggy
	attr=Description

[clothtype-Tank Top]
	Check=TankTop
	attr=Color
		Value=Black
		Value=Blue
		Value=Brown
		Value=Green
		Value=Grey
		Value=Orange
		Value=Pink
		Value=Purple
		Value=Red
		Value=Tan
		Value=White
		Value=Yellow
		Value=?
	attr=Material
		value=Cloth
		value=Latex
		value=Leather
		value=PVC
	attr=Style
		Value=Tight
		Value=Loose
		Value=Baggy
	attr=Description



;*******************************************************************
;* Cloth types - Bottoms
;*******************************************************************
[clothtype-Dress]
	Check=Dress
	attr=Color
		Value=Black
		Value=Blue
		Value=Brown
		Value=Green
		Value=Grey
		Value=Orange
		Value=Pink
		Value=Purple
		Value=Red
		Value=Tan
		Value=White
		Value=Yellow
		Value=?
	attr=Length
		Value=Above the Knee
		Value=Below the Knee
		Value=Ankle Length
	attr=Material
		value=Cloth
		value=Latex
		value=Leather
		value=PVC
	attr=Description

[clothtype-Mini-Skirt]
	Check=Mini-Skirt
	attr=Color
		Value=Black
		Value=Blue
		Value=Brown
		Value=Green
		Value=Grey
		Value=Orange
		Value=Pink
		Value=Purple
		Value=Red
		Value=Tan
		Value=White
		Value=Yellow
		Value=?
	attr=Length
		Value=Below the Butt Cheeks
		Value=Above the Butt Cheeks
	attr=Material
		value=Cloth
		value=Latex
		value=Leather
		value=PVC
	attr=Description

[clothtype-Pants]
	Check=Pants
	attr=Color
		Value=Black
		Value=Blue
		Value=Brown
		Value=Green
		Value=Grey
		Value=Orange
		Value=Pink
		Value=Purple
		Value=Red
		Value=Tan
		Value=White
		Value=Yellow
		Value=?
	attr=Length
		Value=Calf Length
		Value=Ankle Length
	attr=Material
		value=Cloth
		value=Latex
		value=Leather
		value=PVC
	attr=Style
		Value=Tight
		Value=Loose
		Value=Baggy
	attr=Description

[clothtype-Shorts]
	Check=Shorts
	attr=Color
		Value=Black
		Value=Blue
		Value=Brown
		Value=Green
		Value=Grey
		Value=Orange
		Value=Pink
		Value=Purple
		Value=Red
		Value=Tan
		Value=White
		Value=Yellow
		Value=?
	attr=Length
		Value=Below the Butt Cheeks
		Value=Above the Butt Cheeks
		Value=Above the Knee
		Value=Below the Knee
	attr=Material
		value=Cloth
		value=Latex
		value=Leather
		value=PVC
	attr=Description

[clothtype-Skirt]
	Check=Skirt
	attr=Color
		Value=Black
		Value=Blue
		Value=Brown
		Value=Green
		Value=Grey
		Value=Orange
		Value=Pink
		Value=Purple
		Value=Red
		Value=Tan
		Value=White
		Value=Yellow
		Value=?
	attr=Length
		Value=Above the Knee
		Value=Below the Knee
		Value=Ankle Length
	attr=Material
		value=Cloth
		value=Latex
		value=Leather
		value=PVC
	attr=Description

[clothtype-Sundress]
	Check=Sundress
	attr=Color
		Value=Black
		Value=Blue
		Value=Brown
		Value=Green
		Value=Grey
		Value=Orange
		Value=Pink
		Value=Purple
		Value=Red
		Value=Tan
		Value=White
		Value=Yellow
		Value=?
	attr=Length
		Value=Above the Knee
		Value=Below the Knee
		Value=Ankle Length
	attr=Material
		value=Cloth
		value=Latex
		value=Leather
		value=PVC
	attr=Description

;*******************************************************************
;* Cloth types - Underwear
;*******************************************************************
[clothtype-Bra and Bustier]
	Check=Bra
	attr=Color
		Value=Black
		Value=Blue
		Value=Brown
		Value=Green
		Value=Grey
		Value=Orange
		Value=Pink
		Value=Purple
		Value=Red
		Value=Tan
		Value=White
		Value=Yellow
		Value=?
	attr=Material
		value=Cloth
		value=Latex
		value=Leather
		value=PVC
	attr=style
		value=Full Cup
		value=Half Cup
		value=Pushup
		value=Platform
		value=Sports
		value=Bustier
	attr=clasp
		value=front clasp
		value=back clasp
	attr=Description

[clothtype-Corset]
	Check=Corset
	attr=Color
		Value=Black
		Value=Blue
		Value=Brown
		Value=Green
		Value=Grey
		Value=Orange
		Value=Pink
		Value=Purple
		Value=Red
		Value=Tan
		Value=White
		Value=Yellow
		Value=?
	attr=Lacing
		value=Front Lacing
		value=Back Lacing
		value=Side Lacing
	attr=Bust Type
   		value=Covering bust
		value=Open cup
		value=Below bust
	attr=Garter straps
		value=None
		value=4
		value=6
		value=8
	attr=Material
		value=Cloth
		value=Latex
		value=Leather
		value=PVC
	attr=Strap Type
		value=Over the Shoulder
		value=Strapless
	attr=Waist size
	attr=Description
		
		

[clothtype-Hoisery]
	attr=Type
		value=Pantyhose
		value=Stockings
		value=Socks
	attr=Color
		Value=Black
		Value=Blue
		Value=Brown
		Value=Green
		Value=Grey
		Value=Orange
		Value=Pink
		Value=Purple
		Value=Red
		Value=Tan
		Value=White
		Value=Yellow
		Value=?
	attr=Length
		value=Above knee
		value=Ankle
		value=Below knee
		Value=Full Length
		value=Thigh
	attr=Material
		value=Cotton
		value=Latex
		value=Nylon
		value=Silk
	attr=Description

[clothtype-Underwear]
	Check=Underwear
	attr=Color
		Value=Black
		Value=Blue
		Value=Brown
		Value=Green
		Value=Grey
		Value=Orange
		Value=Pink
		Value=Purple
		Value=Red
		Value=Tan
		Value=White
		Value=Yellow
		Value=?
	attr=Material
		value=Cloth
		value=Latex
		value=Leather
		value=PVC
	attr=Style
		Value=Boyshorts
		Value=Boxers
		Value=Briefs
		Value=Cotton
		Value=Crotchless
		Value=Lace
		Value=Mesh
		Value=Thong
	attr=Description

;*******************************************************************
;* Cloth types - Shoes
;*******************************************************************
[clothtype-Shoes]
	attr=Color
		Value=Black
		Value=Blue
		Value=Brown
		Value=Green
		Value=Grey
		Value=Orange
		Value=Pink
		Value=Purple
		Value=Red
		Value=Tan
		Value=White
		Value=Yellow
		Value=?
	attr=Style
		value=Ballet Boots
		value=Boots
		value=Dress Shoes
		value=Flats
		value=Pumps
		value=Sandals
		value=Tennis shoes
	attr=Heel height
		value=No heels
		value=1"
		value=2"
		Value=3"
		Value=4"
		Value=5"
		Value=6"
		Value=7"
		Value=8"
	attr=Heel type
		value=Normal
		value=Spike
		value=Stilletto
	attr=Description

;*******************************************************************
;* Cloth types - Sleep
;*******************************************************************

;*******************************************************************
;* Cloth types - Bondage Items
;*******************************************************************
[clothtype-Collar]
	attr=Color
		Value=Black
		Value=Blue
		Value=Brown
		Value=Green
		Value=Grey
		Value=Orange
		Value=Pink
		Value=Purple
		Value=Red
		Value=Tan
		Value=White
		Value=Yellow
		Value=?
	attr=Material
		value=Latex
		value=Leather
		value=Steel
		value=?
	attr=Type
		Value=Normal
		value=Posture
	attr=Width
		value=1"
		value=2"
		value=3"
		value=4"
		value=5"
		value=6"
	attr=Description

[clothtype-Cuffs]
	attr=material
		value=Latex
		value=Leather
		value=Steel
	attr=Description

[clothtype-Gag]
	attr=Color
		Value=Black
		Value=Blue
		Value=Brown
		Value=Green
		Value=Grey
		Value=Orange
		Value=Pink
		Value=Purple
		Value=Red
		Value=Tan
		Value=White
		Value=Yellow
		Value=?
	attr=Style
		value=Ball
		value=Bit
		value=Dental
		value=Inflatable
		value=Penis
		value=Ring
		value=?
	attr=Description


[clothtype-Leash]
	attr=material
		value=Chain
		value=Latex
		value=Leather
	attr=Description

[clothtype-Other Bondage Items]
	attr=Description
	attr=Color
		Value=Black
		Value=Blue
		Value=Brown
		Value=Green
		Value=Grey
		Value=Orange
		Value=Pink
		Value=Purple
		Value=Red
		Value=Tan
		Value=White
		Value=Yellow
		Value=?