;*******************************************************************
;* Instructions
;*******************************************************************
[Instructions-Get the Mail]
	change=Daily
	none=No special instructions
	choice=new
		option=Hobble your legs.
		option=*
			weight=5
	choice=new
		option=Carry the mail in your mouth.
		option=*
			weight=5
	choice=new
		option=Bind yourself in a karda.
		option=*
			weight=5
	choice=new
		option=Crawl to the mailbox.
		option=*
			weight=5
	choice=new
		notif=#eButtPlug=0
		option=Wear a butt plug.
		option=*
			weight=5
	choice=new
		notif=#pPublicHumiliation=0
		option=You must be naked.
		option=*
			weight=5